system('subst s: /d');
system('subst o: /d');
system('subst p: /d');

rootdir = ['C:\Documents and Settings\Linda Group\My Documents\MATLAB\polymer_calcs\data\MeLPPP\'];
SFolder = 'Exp';
OFolder = 'INDOLib';
PFolder = 'GSLib';

system(['subst s: "',rootdir,SFolder,'"']);
system(['subst o: "',rootdir,OFolder,'"']);
system(['subst p: "',rootdir,PFolder,'"']);

myece = ECEParams('AM1', {}, true, 0.0, 2000, 25, 's:\NoAngle\ExploreDipoleNewAlg\param_template.txt');
myexp = EnergyCalcExp(myece,...
    's:\NoAngle\MeLPPP-8mer.dat',...
    [3 118],...
    ['s:\NoAngle\ExploreDipoleNewAlg\MeLPPP-8mer-NewAlg-',num2str(0.0),'VA.mat'],...
    'o:\',...
    'p:\',...
    false,...
    ['Ladder Polymer Field Study - ',num2str(0.0),'VA']);
myexp.run('quiet');

last_indo_hash = myexp.data(1).indo_hash;
    
for fs = 0.001:0.001:0.2
    myece = ECEParams('AM1', {}, true, fs, 2000, 25, 's:\NoAngle\ExploreDipoleNewAlg\param_template.txt');
    myece.dm_guess = ['"o:\', last_indo_hash, '-dm.bin"'];
    myexp = EnergyCalcExp(myece,...
        's:\NoAngle\MeLPPP-8mer.dat',...
        [3 118],...
        ['s:\NoAngle\ExploreDipoleNewAlg\MeLPPP-8mer-NewAlg-',num2str(fs),'VA.mat'],...
        'o:\',...
        'p:\',...
        false,...
        ['Ladder Polymer Field Study - ',num2str(fs),'VA']);
    myexp.run('quiet');
    last_indo_hash = myexp.data(1).indo_hash;
end